### ISSUE TITLE
Exception raised when closing arch dialog

### ISSUE THREAD

**Issue by daniellimws** [orppra/ropa#47]
```
Traceback (most recent call last):
  File "/home/daniel/ropa/ropa/gui/gui.py", line 141, in <lambda>
    button.triggered.connect(lambda: func())
  File "/home/daniel/ropa/ropa/gui/controller/menu_item_controller.py", line 15, in start_new_project
    filepath, arch = self.file_dialog_controller.new_file_dialog(filepath)
  File "/home/daniel/ropa/ropa/gui/controller/file_dialog_controller.py", line 17, in new_file_dialog
    raise Exception('Failed to open dialog')
Exception: Failed to open dialog
```

Exception raised when closing dialog to choose architecture.
I don't think this is necessary, in cases where the user misclicked on a wrong file.

**Comment by daniellimws** [comment]
Probably can remove the arch choosing dialog entirely, and let ropper auto-detect.
